export https_proxy=...
export http_proxy=...
export all_proxy=...
docker_user=...
tag=$(date +%Y%m%d)

docker tag transformers:ds $docker_user/transformers:ds_$tag
docker push $docker_user/transformers:ds_$tag
docker tag belle:$tag $docker_user/belle:$tag
docker push $docker_user/belle:$tag
docker tag belle:$tag $docker_user/belle:latest
docker push $docker_user/belle:latest